server:
  host: 127.0.0.1
  port: 8080
  ssl:
    enabled: true
    cert_file: examples/certs/server.crt
    key_file: examples/certs/server.key

logging:
  level: info
  pretty: true

database:
  driver: sqlite3
  dsn: file:examples/dev.db?cache=shared
